### ISSUE TITLE
use `/usr/local/share` instead of `/usr/share`

### ISSUE THREAD

**Issue by dnkmmr69420** [ivan-hc/Firefox-for-Linux-scripts#1]
This won't work on immutable linux distros because of this.

**Comment by ivan-hc** [comment]
Try to install it with "[AM](https://github.com/ivan-hc/AM-Application-Manager)" (system wide) or [AppMan](https://github.com/ivan-hc/AppMan) (locally).

"AM" already patches these scripts in case the distro is immutable and the path become /usr/local/share/applications for the launchers and /opt for the app.

Command `am -i firefox`

**Comment by ivan-hc** [comment]
I have added a function to check the immutability of the distro:
```
if [[ $(grep "[[:space:]]ro[[:space:],]" /proc/mounts) ]]; then
	mkdir -p /usr/local/share/applications
	sed -i 's#/usr/share/applications#/usr/local/share/applications#g' ./$arg
	SHARE_APPLICATIONS="local/share/applications"
else
	SHARE_APPLICATIONS="share/applications"
fi
```
if the distro has Read Only mountpoints in /proc/mounts, then the script will create the directory /usr/local/share/applications and that will be the place where all launchers will be placed.

I've updated also the scripts for the 32-bit version... but I don't think that there are 32-bits immutable distros.
