### ISSUE TITLE
Add shortened versions

### ISSUE THREAD

**Issue by 1280px** [ivan-hc/Firefox-for-Linux-scripts#3]
Thanks for neat scripts, but it would be nicer if there were shortened install commands provided as well, easier to type out from keyboard character by character. Below is an example for a part of README (link shortener taken from [awesome-url-shortener](https://github.com/738/awesome-url-shortener)):

# Firefox Beta

### Install (64 bit):
`wget https://raw.githubusercontent.com/ivan-hc/Firefox-for-Linux-scripts/main/firefox-beta && chmod a+x ./firefox-beta && sudo ./firefox-beta`

**Shortlink:** `wget 73.nu/2qg -O I && chmod -x I && sudo ./I`

### Install (32 bit):

...

**Comment by ivan-hc** [comment]
Hi, you can simply copy/paste the commands in your terminal, no need to write everything again.

Anyway, for a faster experience, I suggest to install AM https://github.com/ivan-hc/AM and then run the following command
```
am -i firefox-beta
```
you can also install it in a rootless way
```
am -i --user firefox-beta
```
or if you choose to use AppMan (still rootless)
```
appman -i firefox-beta
```
you can install more than 2500 programs using the AM database, or more than 5000 if we include the third-party repo of Toolpacks.

Check it out https://github.com/ivan-hc/AM

-------------------------

About shorter URLs, its a transparency matter. I try to do things in an as much transparent way as possible. To show the full raw URL is one of these things.
